function createfigure(X1, Y1, Z1, XMatrix1, YMatrix1, ZMatrix1, XMatrix2, YMatrix2, ZMatrix2)
%CREATEFIGURE(X1, Y1, Z1, XMatrix1, YMatrix1, ZMatrix1, XMatrix2, YMatrix2, ZMatrix2)
%  X1:  vector of plot3 x data
%  Y1:  vector of plot3 y data
%  Z1:  vector of plot3 z data
%  XMATRIX1:  matrix of plot3 x data
%  YMATRIX1:  matrix of plot3 y data
%  ZMATRIX1:  matrix of plot3 z data
%  XMATRIX2:  matrix of plot3 x data
%  YMATRIX2:  matrix of plot3 y data
%  ZMATRIX2:  matrix of plot3 z data

%  Auto-generated by MATLAB on 07-Jan-2024 19:26:55

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1],...
    'OuterPosition',[142 12 1105 1039]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1,'DisplayName','Target Trajectory','LineWidth',2,...
    'LineStyle',':',...
    'Color',[0 0 0]);

% Create multiple line objects using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'LineStyle',':','Color',[1 0 0]);
set(plot31(2003),'DisplayName','Chaser Range of Vision','LineStyle','-');

% Create multiple line objects using matrix input to plot3
plot32 = plot3(XMatrix2,YMatrix2,ZMatrix2,'MarkerSize',12,'Marker','.',...
    'LineStyle','none');
set(plot32(1),...
    'DisplayName','Chaser Trajectory -- In range (Physical Model)',...
    'Color',[1 0 0]);
set(plot32(2),...
    'DisplayName','Chaser Trajectory -- Setpoint Tracking (Physical Model)',...
    'Color',[0 1 0]);

% Create zlabel
zlabel('z position [m]','FontSize',11,'Interpreter','latex');

% Create ylabel
ylabel('y position [m]','FontSize',11,'Interpreter','latex');

% Create xlabel
xlabel('x position [m]','FontSize',11,'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-100 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-100 1000]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 150]);
view(axes1,[-98.7915559030492 46.1853211009174]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',11);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',"northoutside",...
    'Interpreter','latex',...
    'FontSize',16.2);

